import type { Metadata } from "next";
import { Inter, Prompt } from "next/font/google";
import "./globals.css";
import { CustomProviders } from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "RMS V.2",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <CustomProviders>
      <html lang="en">
        <body className={inter.className}>
            <div className="mx-auto min-h-screen">
              {children}
            </div>
        </body>
      </html>
    </CustomProviders>
  );
}
